import { SITE_NAME } from '@/lib/config/site';
import type { DailyReportData } from '@/lib/email/reports/gather';

export interface DailyReportTemplateInput {
  data: DailyReportData;
  siteName?: string;
}

/**
 * M25 — daily report email template.
 *
 * Renders the same KPIs as /admin/reports: total requests, cache hit
 * rate, avg latency, failed refresh jobs (24h), plus top 5 repos and
 * the GitHub token quota snapshot.
 */
export function dailyReportTemplate(input: DailyReportTemplateInput): {
  subject: string;
  html: string;
  text: string;
} {
  const site = input.siteName ?? SITE_NAME;
  const dateLabel = input.data.dateLabel;
  const subject = `${site} daily report — ${dateLabel}`;
  const d = input.data;

  const repoRows = d.topRepos
    .map(
      (r) =>
        `<tr><td style="padding:6px 12px;border-bottom:1px solid #eee;"><code>${escapeHtml(r.repo)}</code></td><td style="padding:6px 12px;text-align:right;">${r.requestCount.toLocaleString()}</td><td style="padding:6px 12px;text-align:right;">${(r.hitRate * 100).toFixed(1)}%</td></tr>`,
    )
    .join('');

  const html = `<!doctype html>
<html lang="en">
  <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.5; color: #111;">
    <h1 style="font-size:20px;margin:0 0 4px 0;">${escapeHtml(site)} — daily report</h1>
    <p style="color:#666;margin:0 0 16px 0;">${escapeHtml(dateLabel)}</p>

    <h2 style="font-size:16px;margin:24px 0 8px 0;">Key metrics</h2>
    <table style="border-collapse:collapse;width:100%;max-width:480px;">
      <tr><td style="padding:6px 12px;">Total requests</td><td style="padding:6px 12px;text-align:right;font-weight:bold;">${d.totalRequests.toLocaleString()}</td></tr>
      <tr><td style="padding:6px 12px;">Cache hit rate</td><td style="padding:6px 12px;text-align:right;font-weight:bold;">${(d.cacheHitRate * 100).toFixed(1)}%</td></tr>
      <tr><td style="padding:6px 12px;">Avg latency</td><td style="padding:6px 12px;text-align:right;font-weight:bold;">${d.avgLatencyMs.toFixed(0)} ms</td></tr>
      <tr><td style="padding:6px 12px;">Failed jobs (24h)</td><td style="padding:6px 12px;text-align:right;font-weight:bold;color:${d.failedJobs24h > 0 ? '#b91c1c' : '#111'};">${d.failedJobs24h.toLocaleString()}</td></tr>
    </table>

    <h2 style="font-size:16px;margin:24px 0 8px 0;">Top repositories</h2>
    ${
      d.topRepos.length === 0
        ? '<p style="color:#666;">No requests in this window.</p>'
        : `<table style="border-collapse:collapse;width:100%;">
        <thead><tr><th style="text-align:left;padding:6px 12px;border-bottom:1px solid #ccc;">Repo</th><th style="text-align:right;padding:6px 12px;border-bottom:1px solid #ccc;">Requests</th><th style="text-align:right;padding:6px 12px;border-bottom:1px solid #ccc;">Hit rate</th></tr></thead>
        <tbody>${repoRows}</tbody>
      </table>`
    }

    <h2 style="font-size:16px;margin:24px 0 8px 0;">GitHub token quota</h2>
    ${
      d.tokenQuotaUsage.length === 0
        ? '<p style="color:#666;">No tokens registered.</p>'
        : `<ul>${d.tokenQuotaUsage.map((t) => `<li><code>${escapeHtml(t.label)}</code> — ${t.requestsUsed.toLocaleString()} / ${t.requestsLimit.toLocaleString()}</li>`).join('')}</ul>`
    }

    <hr style="margin-top:32px;">
    <p style="color:#999;font-size:12px;">Window: ${escapeHtml(d.windowStartUtc)} → ${escapeHtml(d.windowEndUtc)} (UTC). Auto-generated by ${escapeHtml(site)}.</p>
  </body>
</html>`;

  const text = [
    `${site} — daily report`,
    dateLabel,
    '',
    'Key metrics',
    `  Total requests:    ${d.totalRequests.toLocaleString()}`,
    `  Cache hit rate:    ${(d.cacheHitRate * 100).toFixed(1)}%`,
    `  Avg latency:       ${d.avgLatencyMs.toFixed(0)} ms`,
    `  Failed jobs (24h): ${d.failedJobs24h.toLocaleString()}`,
    '',
    'Top repositories',
    ...(d.topRepos.length === 0
      ? ['  No requests in this window.']
      : d.topRepos.map((r) => `  ${r.repo} — ${r.requestCount} requests, ${(r.hitRate * 100).toFixed(1)}% hit`)),
    '',
    'GitHub token quota',
    ...(d.tokenQuotaUsage.length === 0
      ? ['  No tokens registered.']
      : d.tokenQuotaUsage.map((t) => `  ${t.label} — ${t.requestsUsed.toLocaleString()} / ${t.requestsLimit.toLocaleString()}`)),
    '',
    `Window: ${d.windowStartUtc} → ${d.windowEndUtc} (UTC)`,
    `Auto-generated by ${site}.`,
  ].join('\n');

  return { subject, html, text };
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
